# Generated by Django 5.2.10 on 2026-01-22 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('erp_projects', '0006_remove_worklog_story_points_task_story_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('developer', 'Developer'), ('artist', 'Artist'), ('qa', 'QA')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('is_allowed', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('role', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_override', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('developer', 'Developer'), ('artist', 'Artist'), ('qa', 'QA')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
