# Generated by Django 4.2.27 on 2026-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetversion",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="assets/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="assetversion",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetversion",
            name="file_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="assetversion",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="assetversion",
            name="file_path",
            field=models.CharField(
                blank=True, help_text="S3 Key or external URL", max_length=500
            ),
        ),
    ]
