# Generated by Django 5.2.10 on 2026-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_projects', '0002_task_due_date_sprint_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(default=0),
        ),
    ]
