# Generated by Django 5.2.10 on 2026-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_projects', '0004_remove_task_story_points_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='story_points',
            field=models.IntegerField(default=0),
        ),
    ]
