# Generated by Django 5.2.10 on 2026-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_projects', '0005_worklog_story_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='story_points',
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(default=0),
        ),
    ]
