# Generated by Django 5.2.10 on 2026-01-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_projects', '0006_remove_worklog_story_points_task_story_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Budget'), ('T&M', 'Time & Materials')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
