# Generated by Django 5.2.10 on 2026-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_projects', '0009_task_priority_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
    ]
