# Generated by Django 4.2.27 on 2026-01-24 10:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("hire_date", models.DateField()),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, help_text="Annual salary", max_digits=10
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=100)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether employee is currently active"
                    ),
                ),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ENGINE", "Game Engine"),
                            ("PROGRAMMING", "Programming Language"),
                            ("ART", "Art Tool"),
                            ("AUDIO", "Audio Tool"),
                            ("DESIGN", "Design Tool"),
                            ("SOFT_SKILL", "Soft Skill"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("QUARTERLY", "Quarterly Review"),
                            ("ANNUAL", "Annual Review"),
                            ("PROJECT", "Project-Based Review"),
                            ("PROBATION", "Probation Review"),
                            ("ADHOC", "Ad-hoc Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("review_date", models.DateField()),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "strengths",
                    models.TextField(help_text="Employee's strengths and achievements"),
                ),
                (
                    "areas_for_improvement",
                    models.TextField(help_text="Areas that need improvement"),
                ),
                ("goals", models.TextField(help_text="Goals for next review period")),
                (
                    "technical_skills_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "teamwork_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "problem_solving_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ]
                    ),
                ),
                (
                    "leadership_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Needs Improvement"),
                            (2, "Meets Expectations"),
                            (3, "Exceeds Expectations"),
                            (4, "Outstanding"),
                            (5, "Exceptional"),
                        ],
                        help_text="N/A for non-leadership roles",
                        null=True,
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, help_text="Additional comments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="hr.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review",
                "verbose_name_plural": "Performance Reviews",
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("SICK", "Sick Leave"),
                            ("VACATION", "Vacation"),
                            ("PERSONAL", "Personal Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("UNPAID", "Unpaid Leave"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("approval_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual budget for department",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to="hr.employee",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_departments",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Intermediate"),
                            (3, "Advanced"),
                            (4, "Expert"),
                            (5, "Master"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "years_experience",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Years of experience with this skill",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Relevant certifications or qualifications",
                    ),
                ),
                (
                    "last_used",
                    models.DateField(
                        blank=True,
                        help_text="When this skill was last used in a project",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="hr.employee",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="hr.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Skill",
                "verbose_name_plural": "Employee Skills",
                "ordering": ["-proficiency", "-years_experience"],
                "unique_together": {("employee", "skill")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("HALF_DAY", "Half Day"),
                            ("WORK_FROM_HOME", "Work From Home"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Reason for absence/late/etc."
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overtime hours worked",
                        max_digits=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "employee"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
