# Generated by Django 4.2.27 on 2026-01-24 10:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("erp_projects", "0010_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("client_name", models.CharField(max_length=200)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_address", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="NET 30",
                        help_text="Payment terms (e.g., NET 30, Due on Receipt)",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or payment instructions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="erp_projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revenue_type",
                    models.CharField(
                        choices=[
                            ("PROJECT_PAYMENT", "Project Payment"),
                            ("RETAINER", "Retainer Fee"),
                            ("CONSULTING", "Consulting Income"),
                            ("LICENSING", "Licensing Revenue"),
                            ("TRAINING", "Training Revenue"),
                            ("SUPPORT", "Support Contract"),
                            ("OTHER", "Other Revenue"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date", models.DateField()),
                ("client_name", models.CharField(max_length=200)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHECK", "Check"),
                            ("CASH", "Cash"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("PAYPAL", "PayPal"),
                            ("CRYPTO", "Cryptocurrency"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.invoice",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue",
                        to="erp_projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue",
                "verbose_name_plural": "Revenue Records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("P&L", "Profit & Loss"),
                            ("BALANCE_SHEET", "Balance Sheet"),
                            ("CASH_FLOW", "Cash Flow Statement"),
                            ("PROJECT_REPORT", "Project Financial Report"),
                            ("DEPARTMENT_REPORT", "Department Financial Report"),
                            ("EXPENSE_REPORT", "Expense Report"),
                            ("REVENUE_REPORT", "Revenue Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "data_summary",
                    models.JSONField(
                        default=dict, help_text="Report summary data in JSON format"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether report is accessible to all users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Report",
                "verbose_name_plural": "Financial Reports",
                "ordering": ["-generated_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SOFTWARE", "Software & Licenses"),
                            ("HARDWARE", "Hardware & Equipment"),
                            ("OFFICE", "Office Supplies"),
                            ("MARKETING", "Marketing & Advertising"),
                            ("TRAVEL", "Travel & Entertainment"),
                            ("TRAINING", "Training & Education"),
                            ("UTILITIES", "Utilities"),
                            ("RENT", "Rent & Lease"),
                            ("INSURANCE", "Insurance"),
                            ("LEGAL", "Legal & Professional"),
                            ("BANK_FEES", "Bank Fees"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "vendor",
                    models.CharField(
                        help_text="Company or individual paid to", max_length=200
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="receipts/%Y/%m/%d/"
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=100)),
                ("tax_deductible", models.BooleanField(default=True)),
                ("approved", models.BooleanField(default=False)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for company-wide expenses",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="erp_projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("PROJECT", "Project Budget"),
                            ("DEPARTMENT", "Department Budget"),
                            ("OPERATIONAL", "Operational Budget"),
                            ("MARKETING", "Marketing Budget"),
                            ("CAPITAL", "Capital Expenditure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="erp_projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="Payroll month (first day of month)"),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bonuses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHECK", "Check"),
                            ("CASH", "Cash"),
                            ("DIGITAL", "Digital Wallet"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=50,
                    ),
                ),
                ("bank_account", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_records",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payroll Records",
                "ordering": ["-month", "employee"],
                "unique_together": {("employee", "month")},
            },
        ),
    ]
